# permissions for end users to view hostedcontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostedcontrolplane-viewer-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - hostedcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - hostedcontrolplanes/status
  verbs:
  - get
